"""Models for the Billing Subscriptions resource (Company API v2)."""

from __future__ import annotations

import datetime as dt

from ..._models import Money, PennylaneModel

__all__ = [
    "BillingSubscription",
    "BillingSubscriptionCustomer",
    "BillingSubscriptionCustomerInvoiceData",
    "BillingSubscriptionCustomerInvoiceTemplate",
    "BillingSubscriptionDiscount",
    "BillingSubscriptionEmailSettings",
    "BillingSubscriptionEmailTemplate",
    "BillingSubscriptionInvoiceLine",
    "BillingSubscriptionInvoiceLineImputationDates",
    "BillingSubscriptionInvoiceLineProduct",
    "BillingSubscriptionInvoiceLineSection",
    "BillingSubscriptionInvoiceLinesLink",
    "BillingSubscriptionRecurringRule",
]


class BillingSubscriptionEmailTemplate(PennylaneModel):
    """Billing email template referenced by a subscription's email settings."""

    id: int | None = None
    label: str | None = None


class BillingSubscriptionEmailSettings(PennylaneModel):
    """Email delivery settings of a billing subscription."""

    recipients: list[str] | None = None
    billing_email_template: BillingSubscriptionEmailTemplate | None = None


class BillingSubscriptionRecurringRule(PennylaneModel):
    """Recurrence rule of a billing subscription."""

    day_of_month: list[float] | None = None
    month_of_year: list[float] | None = None
    week_start: float | None = None
    day: list[float] | None = None
    rule_type: str | None = None
    interval: int | None = None
    count: int | None = None
    until: str | None = None


class BillingSubscriptionCustomer(PennylaneModel):
    """Customer linked to a billing subscription."""

    id: int | None = None
    url: str | None = None


class BillingSubscriptionCustomerInvoiceTemplate(PennylaneModel):
    """Customer invoice template referenced by a subscription's invoice data."""

    id: int | None = None


class BillingSubscriptionDiscount(PennylaneModel):
    """A discount applied on an invoice or an invoice line."""

    type: str | None = None
    value: Money | None = None


class BillingSubscriptionInvoiceLinesLink(PennylaneModel):
    """A link to the invoice lines or invoice line sections of a subscription."""

    url: str | None = None


class BillingSubscriptionCustomerInvoiceData(PennylaneModel):
    """The invoice template data generated for each subscription occurrence."""

    label: str | None = None
    currency: str | None = None
    amount: Money | None = None
    currency_amount: Money | None = None
    currency_amount_before_tax: Money | None = None
    exchange_rate: Money | None = None
    currency_tax: Money | None = None
    language: str | None = None
    customer_invoice_template: BillingSubscriptionCustomerInvoiceTemplate | None = None
    discount: BillingSubscriptionDiscount | None = None
    pdf_invoice_free_text: str | None = None
    pdf_invoice_subject: str | None = None
    pdf_description: str | None = None
    special_mention: str | None = None
    invoice_line_sections: BillingSubscriptionInvoiceLinesLink | None = None
    invoice_lines: BillingSubscriptionInvoiceLinesLink | None = None


class BillingSubscription(PennylaneModel):
    """A billing subscription used to generate recurring customer invoices.

    Reference: https://pennylane.readme.io/reference/getbillingsubscription
    """

    id: int
    next_occurrence: dt.date | None = None
    prev_occurrence: dt.date | None = None
    stopped_at: dt.datetime | None = None
    start: dt.date | None = None
    finish: dt.date | None = None
    status: str | None = None
    mode: str | None = None
    activated_at: dt.datetime | None = None
    payment_conditions: str | None = None
    payment_method: str | None = None
    label: str | None = None
    email_settings: BillingSubscriptionEmailSettings | None = None
    recurring_rule: BillingSubscriptionRecurringRule | None = None
    customer: BillingSubscriptionCustomer | None = None
    customer_invoice_data: BillingSubscriptionCustomerInvoiceData | None = None
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None


class BillingSubscriptionInvoiceLineProduct(PennylaneModel):
    """Product referenced by a billing subscription invoice line."""

    id: int | None = None
    url: str | None = None


class BillingSubscriptionInvoiceLineImputationDates(PennylaneModel):
    """Imputation period of a billing subscription invoice line."""

    start_date: dt.date | None = None
    end_date: dt.date | None = None


class BillingSubscriptionInvoiceLine(PennylaneModel):
    """An invoice line generated by a billing subscription.

    Reference: https://pennylane.readme.io/reference/getbillingsubscriptioninvoicelines
    """

    id: int
    label: str | None = None
    unit: str | None = None
    quantity: Money | None = None
    amount: Money | None = None
    currency_amount: Money | None = None
    description: str | None = None
    product: BillingSubscriptionInvoiceLineProduct | None = None
    vat_rate: str | None = None
    currency_amount_before_tax: Money | None = None
    currency_tax: Money | None = None
    tax: Money | None = None
    raw_currency_unit_price: Money | None = None
    discount: BillingSubscriptionDiscount | None = None
    section_rank: int | None = None
    imputation_dates: BillingSubscriptionInvoiceLineImputationDates | None = None
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None


class BillingSubscriptionInvoiceLineSection(PennylaneModel):
    """An invoice line section generated by a billing subscription.

    Reference: https://pennylane.readme.io/reference/getbillingsubscriptioninvoicelinesections
    """

    id: int
    title: str | None = None
    description: str | None = None
    rank: int | None = None
    created_at: dt.datetime | None = None
    updated_at: dt.datetime | None = None
